# Generated by Django 3.0.3 on 2020-02-13 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 22, 19, 38, 437587)),
        ),
    ]
