# Generated by Django 3.0.3 on 2020-02-25 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200218_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 20, 33, 3, 710115)),
        ),
    ]
