# Generated by Django 3.0.3 on 2020-03-11 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200311_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 20, 49, 39, 117788)),
        ),
    ]
